services:
  mysqldb:
    container_name: utils_mysqldb_ci
    build:
      args:
        - MYSQL_VERSION=${MYSQL_CI_VERSION:-5.7}
      context: .
      dockerfile_inline: |
        ARG MYSQL_VERSION 5.7
        FROM mysql:${MYSQL_VERSION:-5.7} AS mysql

        COPY resources/*.sql /docker-entrypoint-initdb.d/
    env_file:
    - ./.env.test
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
      MYSQL_HOST: '127.0.0.1'
    ports:
    - "${MYSQL_CI_HOST_PORT:-23306}:3306"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysql", "-h", "127.0.0.1", "--silent", "-utestuser", "-ptestpassword", "-e", "SELECT 1"]
      interval: 3s
      retries: 5
      start_period: 30s
